auth:
  providers:
    - id: default-twitch
      description: "The default Twitch provider"
      enabled: true
      type: oauth2
      provider_id: twitch
      client_id: ${env:TWITCH_CLIENT_ID}
      client_secret: ${env:TWITCH_CLIENT_SECRET}
