auth:
  providers:
    - id: arcade-miro
      description: "Arcade's default Miro provider"
      enabled: true
      type: oauth2
      provider_id: miro
      client_id: ${env:MIRO_CLIENT_ID}
      client_secret: ${env:MIRO_CLIENT_SECRET}
