auth:
  providers:
    - id: default-tesla
      description: "The default Tesla provider"
      enabled: true
      type: oauth2
      provider_id: tesla
      client_id: ${env:TESLA_CLIENT_ID}
      client_secret: ${env:TESLA_CLIENT_SECRET}