auth:
  providers:
    - id: arcade-squareup
      description: "Arcade's default Square provider"
      enabled: true
      type: oauth2
      provider_id: squareup
      client_id: ${env:SQUARE_CLIENT_ID}
      client_secret: ${env:SQUARE_CLIENT_SECRET}
