import type { ToolkitType } from "@/app/_components/custom/toolkits/toolkits";
export type Tool = {
  name: string;
  image: string;
  summary: string;
  link: string;
  type: ToolkitType;
  category: string;
  isComingSoon?: boolean;
};

export type Category = {
  id: string;
  name: string;
};

export const categories: Category[] = [
  { id: "all", name: "Todas las herramientas" },
  { id: "productivity", name: "Productividad y Documentos" },
  { id: "social", name: "Social y Comunicación" },
  { id: "development", name: "Herramientas para Desarrolladores" },
  { id: "entertainment", name: "Entretenimiento" },
  { id: "search", name: "Búsqueda" },
  { id: "payments", name: "Pagos y Finanzas" },
  { id: "sales", name: "Ventas" },
  { id: "databases", name: "Bases de Datos" },
  { id: "customer-support", name: "Soporte al Cliente" },
];

// Available tools
const availableTools: Tool[] = [
  {
    name: "Gmail",
    image: "gmail.png",
    summary:
      "Envía, escribe, redacta, elimina, trapea y busca correos de Gmail con tus agentes.",
    link: "/toolkits/productivity/gmail",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Slack",
    image: "slack.png",
    summary:
      "Envía y recibe mensajes a canales y usuarios de Slack con agentes",
    link: "/toolkits/social-communication/slack",
    category: "social",
    type: "arcade",
  },
  {
    name: "Slack API",
    image: "slack.png",
    summary:
      "Habilita a los LLMs para interactuar con la API de Slack de bajo nivel",
    link: "/toolkits/social-communication/slack-api",
    category: "social",
    type: "arcade_starter",
  },
  {
    name: "X",
    image: "twitter.png",
    summary:
      "Integra agentes con X (Twitter), incluyendo tweets, usuarios y más",
    link: "/toolkits/social-communication/x",
    category: "social",
    type: "arcade",
  },
  {
    name: "LinkedIn",
    image: "linkedin.png",
    summary:
      "Conéctate e interactúa con la red profesional de LinkedIn a través de tus agentes",
    link: "/toolkits/social-communication/linkedin",
    category: "social",
    type: "arcade",
  },
  {
    name: "Google Calendar",
    image: "google_calendar.png",
    summary:
      "Crea, actualiza, elimina y busca eventos en Google Calendar con tus agentes.",
    link: "/toolkits/productivity/google-calendar",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Google Contacts",
    image: "google_contacts.png",
    summary: "Crea y busca contactos en Google Contacts con tus agentes.",
    link: "/toolkits/productivity/google-contacts",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Google Drive",
    image: "google_drive.png",
    summary: "Lista documentos en Google Drive con tus agentes.",
    link: "/toolkits/productivity/google-drive",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Google Docs",
    image: "google_docs.png",
    summary:
      "Crea, edita y obtén información sobre documentos de Google Docs con tus agentes.",
    link: "/toolkits/productivity/google-docs",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Google Sheets",
    image: "google_sheets.svg",
    summary: "Crea, lee y actualiza Google Sheets con tus agentes.",
    link: "/toolkits/productivity/google-sheets",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Google Slides",
    image: "google_slides.png",
    summary: "Crea, lee y actualiza Google Slides con tus agentes.",
    link: "/toolkits/productivity/google-slides",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "GitHub",
    image: "github.png",
    summary:
      "Interactúa con repositorios, problemas, solicitudes de extracción y más en GitHub",
    link: "/toolkits/development/github/github",
    category: "development",
    type: "arcade",
  },
  {
    name: "E2B",
    image: "e2b.png",
    summary: "Ejecuta y prueba código en un entorno seguro de sandbox",
    link: "/toolkits/development/e2b",
    category: "development",
    type: "arcade",
  },
  {
    name: "Firecrawl",
    image: "firecrawl.png",
    summary: "Navega e interactúa con páginas web de manera programática",
    link: "/toolkits/development/firecrawl/firecrawl",
    category: "development",
    type: "arcade",
  },
  {
    name: "Google Finance",
    image: "google_finance.png",
    summary: "Obtén datos de acciones de Google Finance",
    link: "/toolkits/search/google_finance",
    category: "search",
    type: "arcade",
  },
  {
    name: "Google Flights",
    image: "google_flights.png",
    summary: "Busca vuelos",
    link: "/toolkits/search/google_flights",
    category: "search",
    type: "arcade",
  },
  {
    name: "Google Hotels",
    image: "google_hotels.png",
    summary: "Busca hoteles",
    link: "/toolkits/search/google_hotels",
    category: "search",
    type: "arcade",
  },
  {
    name: "Google Search",
    image: "google_search.png",
    summary: "Realiza búsquedas en Google y recupera información relevante",
    link: "/toolkits/search/google_search",
    category: "search",
    type: "arcade",
  },
  {
    name: "Google Maps",
    image: "google_maps.png",
    summary: "Obtén direcciones entre dos ubicaciones con Google Maps",
    link: "/toolkits/search/google_maps",
    category: "search",
    type: "arcade",
  },
  {
    name: "Google News",
    image: "google_news.png",
    summary: "Busca artículos de noticias con Google News",
    link: "/toolkits/search/google_news",
    category: "search",
    type: "arcade",
  },
  {
    name: "Google Jobs",
    image: "google_jobs.png",
    summary: "Busca ofertas de trabajo con Google Jobs.",
    link: "/toolkits/search/google_jobs",
    category: "search",
    type: "arcade",
  },
  {
    name: "Google Shopping",
    image: "google_shopping.png",
    summary: "Busca productos en Google Shopping.",
    link: "/toolkits/search/google_shopping",
    category: "search",
    type: "arcade",
  },
  {
    name: "Youtube Search",
    image: "youtube.png",
    summary: "Busca y obtén detalles sobre videos de YouTube.",
    link: "/toolkits/search/youtube",
    category: "search",
    type: "arcade",
  },
  {
    name: "Walmart Search",
    image: "walmart.png",
    summary: "Busca y obtén detalles sobre productos listados en Walmart.",
    link: "/toolkits/search/walmart",
    category: "search",
    type: "arcade",
  },
  {
    name: "Spotify",
    image: "spotify.png",
    summary:
      "Controla la reproducción de música y gestiona listas de reproducción en Spotify",
    link: "/toolkits/entertainment/spotify",
    category: "entertainment",
    type: "arcade",
  },
  {
    name: "Imgflip",
    image: "imgflip.jpg",
    summary: "Crea memes con Imgflip",
    link: "/toolkits/entertainment/imgflip",
    category: "entertainment",
    type: "arcade",
  },
  {
    name: "Notion",
    image: "notion.png",
    summary: "Crea, lee y busca páginas de Notion",
    link: "/toolkits/productivity/notion",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Twilio",
    image: "twilio.png",
    summary:
      "Envía mensajes SMS y de WhatsApp a través de la plataforma de Twilio",
    link: "/toolkits/social-communication/twilio/readme",
    category: "social",
    type: "verified",
  },
  {
    name: "Close.io",
    image: "closeio.png",
    summary: "Gestiona leads, contactos y negocios en Close.io CRM",
    link: "/toolkits/productivity/closeio",
    category: "productivity",
    type: "community",
  },
  {
    name: "Obsidian",
    image: "obsidian.png",
    summary: "Crea, edita y gestiona notas de Obsidian",
    link: "/toolkits/productivity/obsidian",
    category: "productivity",
    type: "community",
  },
  {
    name: "Zoom",
    image: "zoom.png",
    summary: "Únete y gestiona reuniones de Zoom con tus agentes",
    link: "/toolkits/social-communication/zoom",
    category: "social",
    type: "arcade",
  },
  {
    name: "Jira",
    image: "atlassian.png",
    summary: "Gestiona proyectos, problemas y más en Jira con tus agentes",
    link: "/toolkits/productivity/jira",
    category: "productivity",
    type: "auth",
  },
  {
    name: "Confluence",
    image: "atlassian.png",
    summary: "Gestiona páginas y espacios de Confluence con tus agentes",
    link: "/toolkits/productivity/confluence",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Outlook Calendar",
    image: "outlook_calendar.svg",
    summary: "Gestiona el calendario de Outlook con tus agentes",
    link: "/toolkits/productivity/outlook-calendar",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Outlook Mail",
    image: "outlook_mail.png",
    summary: "Gestiona correos de Outlook con tus agentes",
    link: "/toolkits/productivity/outlook-mail",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Dropbox",
    image: "dropbox.png",
    summary: "Gestiona archivos y carpetas de Dropbox con tus agentes",
    link: "/toolkits/productivity/dropbox/dropbox",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Discord",
    image: "discord.png",
    summary: "Gestiona servidores, canales y más de Discord con tus agentes",
    link: "/toolkits/social-communication/discord",
    category: "social",
    type: "auth",
  },
  {
    name: "Reddit",
    image: "reddit.png",
    summary: "Interactúa con Reddit con tus agentes",
    link: "/toolkits/social-communication/reddit",
    category: "social",
    type: "arcade",
  },
  {
    name: "Twitch",
    image: "twitch.png",
    summary: "Crea clips, obtén videos y más de Twitch con tus agentes",
    link: "/toolkits/entertainment/twitch",
    category: "entertainment",
    type: "auth",
  },
  {
    name: "Microsoft Teams",
    image: "ms_teams.png",
    summary: "Gestiona equipos, mensajes, chats y canales con tus agentes.",
    link: "/toolkits/social-communication/microsoft-teams",
    category: "social",
    type: "arcade",
    isComingSoon: false,
  },
  {
    name: "Microsoft SharePoint",
    image: "ms_sharepoint.png",
    summary:
      "Gestiona sitios, listas, unidades y archivos de SharePoint con tus agentes.",
    link: "/toolkits/productivity/sharepoint",
    category: "productivity",
    type: "arcade",
    isComingSoon: false,
  },
];

// Coming soon tools
const comingSoonTools: Tool[] = [
  {
    name: "ADP Workforce Now",
    image: "adp.png",
    summary:
      "Gestiona nómina, recursos humanos y datos de la fuerza laboral con tus agentes.",
    link: "/toolkits/productivity/adp",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Aha",
    image: "aha.png",
    summary:
      "Gestiona hojas de ruta de productos y estrategias con tus agentes.",
    link: "/toolkits/productivity/aha",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Airtable",
    image: "airtable.svg",
    summary: "Crea, edita y gestiona bases de Airtable con tus agentes.",
    link: "/toolkits/productivity/airtable",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Amplitude",
    image: "amplitude.png",
    summary:
      "Analiza el comportamiento del usuario y la analítica de productos con tus agentes.",
    link: "/toolkits/productivity/amplitude",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Asana",
    image: "asana.svg",
    summary: "Gestiona proyectos, tareas y más en Asana con tus agentes.",
    link: "/toolkits/productivity/asana",
    category: "productivity",
    type: "arcade",
    isComingSoon: false,
  },
  {
    name: "Ashby",
    image: "ashby.png",
    summary:
      "Gestiona procesos de reclutamiento y contratación con tus agentes.",
    link: "/toolkits/productivity/ashby",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Auth0",
    image: "auth0.svg",
    summary: "Gestiona autenticación y autorización con tus agentes.",
    link: "/toolkits/development/auth0",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "BambooHR",
    image: "bamboohr.png",
    summary:
      "Gestiona datos de empleados y procesos de recursos humanos con tus agentes.",
    link: "/toolkits/productivity/bamboohr",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Basecamp",
    image: "basecamp.png",
    summary:
      "Gestiona proyectos, tareas y comunicación del equipo con tus agentes.",
    link: "/toolkits/productivity/basecamp",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Bill.com",
    image: "bill.png",
    summary: "Gestiona facturas y pagos con tus agentes.",
    link: "/toolkits/productivity/bill",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Bitbucket",
    image: "bitbucket.png",
    summary:
      "Gestiona repositorios, solicitudes de extracción y pipelines con tus agentes.",
    link: "/toolkits/development/bitbucket",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Bluesky",
    image: "bluesky.svg",
    summary: "Interactúa con Bluesky con tus agentes.",
    link: "/toolkits/social-communication/bluesky",
    category: "social",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Box",
    image: "box.svg",
    summary: "Gestiona archivos y carpetas en Box con tus agentes.",
    link: "/toolkits/productivity/box",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Braze",
    image: "braze.png",
    summary: "Gestiona campañas de compromiso del cliente con tus agentes.",
    link: "/toolkits/productivity/braze",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Brex",
    image: "brex.png",
    summary: "Gestiona gastos y tarjetas de negocios con tus agentes.",
    link: "/toolkits/productivity/brex",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Buffer",
    image: "buffer.png",
    summary:
      "Programa y gestiona publicaciones en redes sociales con tus agentes.",
    link: "/toolkits/social-communication/buffer",
    category: "social",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Calendly",
    image: "calendly.svg",
    summary: "Gestiona programación y citas con tus agentes.",
    link: "/toolkits/productivity/calendly",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "ClickUp",
    image: "clickup.svg",
    summary: "Gestiona proyectos, tareas y documentos con tus agentes.",
    link: "/toolkits/productivity/clickup",
    category: "productivity",
    type: "arcade",
    isComingSoon: false,
  },
  {
    name: "Coinbase",
    image: "coinbase.svg",
    summary:
      "Gestiona transacciones y billeteras de criptomonedas con tus agentes.",
    link: "/toolkits/productivity/coinbase",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Datadog",
    image: "datadog.svg",
    summary: "Monitorea aplicaciones e infraestructura con tus agentes.",
    link: "/toolkits/development/datadog",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "DigitalOcean",
    image: "digitalocean.png",
    summary:
      "Gestiona servidores en la nube e infraestructura con tus agentes.",
    link: "/toolkits/development/digitalocean",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "eBay",
    image: "ebay.svg",
    summary: "Gestiona listados, pedidos e inventario en eBay con tus agentes.",
    link: "/toolkits/productivity/ebay",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Evernote",
    image: "evernote.png",
    summary: "Crea y gestiona notas con tus agentes.",
    link: "/toolkits/productivity/evernote",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Factorial",
    image: "factorial.png",
    summary:
      "Gestiona procesos de recursos humanos y datos de empleados con tus agentes.",
    link: "/toolkits/productivity/factorial",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Figma",
    image: "figma.svg",
    summary:
      "Accede a archivos de diseño y colabora en diseños con tus agentes.",
    link: "/toolkits/productivity/figma",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "GitLab",
    image: "gitlab.svg",
    summary:
      "Gestiona repositorios, problemas y solicitudes de fusión con tus agentes.",
    link: "/toolkits/development/gitlab",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Heroku",
    image: "heroku.svg",
    summary: "Despliega y gestiona aplicaciones en Heroku con tus agentes.",
    link: "/toolkits/development/heroku",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Hootsuite",
    image: "hootsuite.png",
    summary: "Gestiona y programa contenido en redes sociales con tus agentes.",
    link: "/toolkits/social-communication/hootsuite",
    category: "social",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "HubSpot",
    image: "hubspot.png",
    summary:
      "Gestiona empresas, contactos, negocios y más en HubSpot con tus agentes.",
    link: "/toolkits/sales/hubspot",
    category: "sales",
    type: "arcade",
    isComingSoon: false,
  },
  {
    name: "Intercom",
    image: "intercom.png",
    summary: "Gestiona comunicaciones y soporte al cliente con tus agentes.",
    link: "/toolkits/social-communication/intercom",
    category: "social",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Linear",
    image: "linear.svg",
    summary: "Gestiona problemas y proyectos con tus agentes.",
    link: "/toolkits/productivity/linear",
    category: "productivity",
    type: "arcade",
    isComingSoon: false,
  },
  {
    name: "Mailchimp",
    image: "mailchimp.png",
    summary:
      "Gestiona campañas de correo electrónico y suscriptores con tus agentes.",
    link: "/toolkits/productivity/mailchimp",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Microsoft Dynamics",
    image: "msft.png",
    summary: "Gestiona procesos de CRM y ERP con tus agentes.",
    link: "/toolkits/productivity/microsoft_dynamics",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Model Context Protocol (MCP)",
    image: "mcp.png",
    summary:
      "Gestiona el contexto y mejora las interacciones de IA con tus agentes.",
    link: "/toolkits/development/mcp",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Miro",
    image: "miro",
    summary: "Crea y colabora en tableros visuales con tus agentes.",
    link: "/toolkits/productivity/miro",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Monday",
    image: "monday.png",
    summary: "Gestiona proyectos y flujos de trabajo con tus agentes.",
    link: "/toolkits/productivity/monday",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Netsuite",
    image: "netsuite.svg",
    summary: "Gestiona operaciones financieras y comerciales con tus agentes.",
    link: "/toolkits/productivity/netsuite",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Okta",
    image: "okta.png",
    summary: "Gestiona identidad y acceso con tus agentes.",
    link: "/toolkits/productivity/okta",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "OneDrive",
    image: "msft.png",
    summary: "Gestiona archivos y carpetas de OneDrive con tus agentes",
    link: "/toolkits/productivity/microsoft/onedrive",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Pinecone",
    image: "pinecone.png",
    summary:
      "Gestiona bases de datos vectoriales y búsqueda de similitud con tus agentes.",
    link: "/toolkits/development/pinecone",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Pinterest",
    image: "pinterest.svg",
    summary: "Crea y gestiona pines y tableros con tus agentes.",
    link: "/toolkits/social-communication/pinterest",
    category: "social",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Pipedrive",
    image: "pipedrive.png",
    summary: "Gestiona pipelines de ventas y leads con tus agentes.",
    link: "/toolkits/productivity/pipedrive",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Plaid",
    image: "plaid.png",
    summary:
      "Conéctate con cuentas financieras y gestiona datos financieros con tus agentes.",
    link: "/toolkits/productivity/plaid",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "QuickBooks",
    image: "quickbooks.png",
    summary: "Gestiona contabilidad y finanzas con tus agentes.",
    link: "/toolkits/productivity/quickbooks",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Salesforce",
    image: "salesforce.svg",
    summary: "Gestiona relaciones con clientes y ventas con tus agentes.",
    link: "/toolkits/sales/salesforce",
    category: "sales",
    type: "arcade",
    isComingSoon: false,
  },
  {
    name: "Shopify",
    image: "shopify.svg",
    summary:
      "Gestiona tiendas de comercio electrónico y productos con tus agentes.",
    link: "/toolkits/productivity/shopify",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "SingleStore",
    image: "singlestore.png",
    summary: "Gestiona bases de datos y operaciones de datos con tus agentes.",
    link: "/toolkits/development/singlestore",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Snowflake",
    image: "snowflake.png",
    summary: "Gestiona almacenes de datos y analíticas con tus agentes.",
    link: "/toolkits/development/snowflake",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Splunk",
    image: "splunk.png",
    summary: "Monitorea y analiza datos de máquinas con tus agentes.",
    link: "/toolkits/development/splunk",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Square",
    image: "square.png",
    summary:
      "Procesa pagos y gestiona operaciones comerciales con tus agentes.",
    link: "/toolkits/productivity/square",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Squarespace",
    image: "squarespace.png",
    summary: "Gestiona sitios web y presencia en línea con tus agentes.",
    link: "/toolkits/productivity/squarespace",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Stripe",
    image: "stripe.svg",
    summary: "Procesa pagos y gestiona suscripciones con tus agentes.",
    link: "/toolkits/payments/stripe",
    category: "payments",
    type: "arcade",
    isComingSoon: false,
  },
  {
    name: "TikTok",
    image: "tiktok.svg",
    summary: "Crea y gestiona contenido de TikTok con tus agentes.",
    link: "/toolkits/social-communication/tiktok",
    category: "social",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Trello",
    image: "trello.png",
    summary: "Gestiona tableros, tarjetas y listas con tus agentes.",
    link: "/toolkits/productivity/trello",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Vercel",
    image: "vercel.svg",
    summary: "Despliega y gestiona aplicaciones web con tus agentes.",
    link: "/toolkits/development/vercel",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Weaviate",
    image: "weaviate.png",
    summary:
      "Gestiona bases de datos vectoriales y búsqueda semántica con tus agentes.",
    link: "/toolkits/development/weaviate",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Workday",
    image: "workday.png",
    summary:
      "Gestiona recursos humanos, finanzas y planificación con tus agentes.",
    link: "/toolkits/productivity/workday",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Wrike",
    image: "wrike.png",
    summary: "Gestiona proyectos y colabora con tus agentes.",
    link: "/toolkits/productivity/wrike",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Xero",
    image: "xero.svg",
    summary: "Gestiona contabilidad y finanzas con tus agentes.",
    link: "/toolkits/productivity/xero",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Zendesk",
    image: "zendesk.png",
    summary: "Gestiona soporte y servicio al cliente con tus agentes.",
    link: "/toolkits/customer-support/zendesk",
    category: "customer-support",
    type: "arcade",
    isComingSoon: false,
  },
  {
    name: "Postgres",
    image: "postgres.svg",
    summary: "Interactúa con bases de datos PostgreSQL con tus agentes.",
    link: "/toolkits/databases/postgres",
    category: "databases",
    type: "community",
    isComingSoon: false,
  },
  {
    name: "Clickhouse",
    image: "clickhouse.svg",
    summary: "Interactúa con bases de datos Clickhouse con tus agentes.",
    link: "/toolkits/databases/clickhouse",
    category: "databases",
    type: "community",
    isComingSoon: false,
  },
  {
    name: "MongoDB",
    image: "mongodb.svg",
    summary: "Interactúa con bases de datos MongoDB con tus agentes.",
    link: "/toolkits/databases/mongodb",
    category: "databases",
    type: "community",
    isComingSoon: false,
  },
];

// Merge and export all tools
export const tools: Tool[] = [...comingSoonTools, ...availableTools];
