export default {
  asana: "Asana",
  confluence: "Confluence",
  dropbox: "Dropbox",
  gmail: "Gmail",
  google_calendar: "Google Calendar",
  google_contacts: "Google Contacts",
  google_docs: "Google Docs",
  google_drive: "Google Drive",
  google_sheets: "Google Sheets",
  jira: "Jira",
  notion: "Notion",
  obsidian: "Obsidian",
  outlook_calendar: "Outlook Calendar",
  outlook_mail: "Outlook Mail",
};
