auth:
  providers:
    - id: default-spotify
      description: "The default Spotify provider"
      enabled: true
      type: oauth2
      provider_id: spotify
      client_id: ${env:SPOTIFY_CLIENT_ID}
      client_secret: ${env:SPOTIFY_CLIENT_SECRET}
