auth:
  providers:
    - id: asana
      description: "Custom Asana provider"
      enabled: true
      type: oauth2
      client_id: ${env:ASANA_CLIENT_ID}
      client_secret: ${env:ASANA_CLIENT_SECRET}

