import { ToolkitType } from "@/components/custom/Toolkits/Toolkits";
export interface Tool {
  name: string;
  image: string;
  summary: string;
  link: string;
  type: ToolkitType;
  category: string;
  isComingSoon?: boolean;
}

export interface Category {
  id: string;
  name: string;
}

export const categories: Category[] = [
  { id: "all", name: "All Tools" },
  { id: "productivity", name: "Productivity & Docs" },
  { id: "social", name: "Social & Communication" },
  { id: "development", name: "Developer Tools" },
  { id: "entertainment", name: "Entertainment" },
  { id: "search", name: "Search" },
];

// Available tools
const availableTools: Tool[] = [
  {
    name: "Gmail",
    image: "gmail.png",
    summary:
      "Send, write, draft, delete, trash, and search Gmail emails with your agents.",
    link: "/toolkits/productivity/google/gmail",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Slack",
    image: "slack.png",
    summary:
      "Send and receive messages to Slack channels and users with agents",
    link: "/toolkits/social-communication/slack",
    category: "social",
    type: "arcade",
  },
  {
    name: "X",
    image: "twitter.png",
    summary:
      "Integrate agents with X (Twitter), including tweets, users, and more",
    link: "/toolkits/social-communication/x",
    category: "social",
    type: "arcade",
  },
  {
    name: "LinkedIn",
    image: "linkedin.png",
    summary:
      "Connect and interact with LinkedIn's professional network through your agents",
    link: "/toolkits/social-communication/linkedin",
    category: "social",
    type: "arcade",
  },
  {
    name: "Google Calendar",
    image: "google_calendar.png",
    summary:
      "Create, update, delete, and search events in Google Calendar with your agents.",
    link: "/toolkits/productivity/google/calendar",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Google Contacts",
    image: "google_contacts.png",
    summary: "Create and search contacts in Google Contacts with your agents.",
    link: "/toolkits/productivity/google/contacts",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Google Drive",
    image: "google_drive.png",
    summary: "List documents in Google Drive with your agents.",
    link: "/toolkits/productivity/google/drive",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Google Docs",
    image: "google_docs.png",
    summary:
      "Create, edit, and get information about Google Docs documents with your agents.",
    link: "/toolkits/productivity/google/docs",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "GitHub",
    image: "github.png",
    summary:
      "Interact with private and public GitHub repositories, issues, pull requests, and more",
    link: "/toolkits/development/github/github",
    category: "development",
    type: "arcade",
  },
  {
    name: "Code Runner",
    image: "e2b.png",
    summary: "Execute and test code in a secure sandbox environment",
    link: "/toolkits/development/code-sandbox",
    category: "development",
    type: "arcade",
  },
  {
    name: "Web",
    image: "web.png",
    summary: "Browse and interact with web pages programmatically",
    link: "/toolkits/development/web/web",
    category: "development",
    type: "arcade",
  },
  {
    name: "Google Finance",
    image: "google_finance.png",
    summary: "Get stock data from Google Finance",
    link: "/toolkits/search/google_finance",
    category: "search",
    type: "arcade",
  },
  {
    name: "Google Flights",
    image: "google_flights.png",
    summary: "Search for flights",
    link: "/toolkits/search/google_flights",
    category: "search",
    type: "arcade",
  },
  {
    name: "Google Hotels",
    image: "google_hotels.png",
    summary: "Search for hotels",
    link: "/toolkits/search/google_hotels",
    category: "search",
    type: "arcade",
  },
  {
    name: "Google Search",
    image: "google_search.png",
    summary: "Perform Google searches and retrieve relevant information",
    link: "/toolkits/search/google_search",
    category: "search",
    type: "arcade",
  },
  {
    name: "Google Maps",
    image: "google_maps.png",
    summary: "Get directions between two locations with Google Maps",
    link: "/toolkits/search/google_maps",
    category: "search",
    type: "arcade",
  },
  {
    name: "Google News",
    image: "google_news.png",
    summary: "Search for news articles with Google News",
    link: "/toolkits/search/google_news",
    category: "search",
    type: "arcade",
  },
  {
    name: "Google Jobs",
    image: "google_jobs.png",
    summary: "Search for job openings with Google Jobs.",
    link: "/toolkits/search/google_jobs",
    category: "search",
    type: "arcade",
  },
  {
    name: "Google Shopping",
    image: "google_shopping.png",
    summary: "Search for products on Google Shopping.",
    link: "/toolkits/search/google_shopping",
    category: "search",
    type: "arcade",
  },
  {
    name: "Youtube Search",
    image: "youtube.png",
    summary: "Search and get details about YouTube videos.",
    link: "/toolkits/search/youtube",
    category: "search",
    type: "arcade",
  },
  {
    name: "Walmart Search",
    image: "walmart.png",
    summary: "Search and get details about products listed on Walmart.",
    link: "/toolkits/search/walmart",
    category: "search",
    type: "arcade",
  },
  {
    name: "Spotify",
    image: "spotify.png",
    summary: "Control music playback and manage playlists on Spotify",
    link: "/toolkits/entertainment/spotify",
    category: "entertainment",
    type: "arcade",
  },
  {
    name: "Notion",
    image: "notion.png",
    summary: "Create, read, and search Notion pages",
    link: "/toolkits/productivity/notion/readme",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Twilio",
    image: "twilio.png",
    summary: "Send SMS and WhatsApp messages through Twilio's platform",
    link: "/toolkits/social-communication/twilio/readme",
    category: "social",
    type: "verified",
  },
  {
    name: "Close.io",
    image: "closeio.png",
    summary: "Manage leads, contacts, and deals in Close.io CRM",
    link: "/toolkits/productivity/closeio",
    category: "productivity",
    type: "community",
  },
  {
    name: "Obsidian",
    image: "obsidian.png",
    summary: "Create, edit, and manage Obsidian notes",
    link: "/toolkits/productivity/obsidian",
    category: "productivity",
    type: "community",
  },
  {
    name: "Zoom",
    image: "zoom.png",
    summary: "Join and manage Zoom meetings with your agents",
    link: "/toolkits/social-communication/zoom",
    category: "social",
    type: "arcade",
  },
  {
    name: "Jira",
    image: "atlassian.png",
    summary: "Manage Jira projects, issues, and more with your agents",
    link: "/toolkits/productivity/jira",
    category: "productivity",
    type: "auth",
  },
  {
    name: "Confluence",
    image: "atlassian.png",
    summary: "Manage Confluence pages and spaces with your agents",
    link: "/toolkits/productivity/confluence",
    category: "productivity",
    type: "auth",
  },
  {
    name: "Outlook",
    image: "msft.png",
    summary: "Manage Outlook emails, calendar, and contacts with your agents",
    link: "/toolkits/productivity/outlook",
    category: "productivity",
    type: "auth",
  },
  {
    name: "OneDrive",
    image: "msft.png",
    summary: "Manage OneDrive files and folders with your agents",
    link: "/toolkits/productivity/onedrive",
    category: "productivity",
    type: "auth",
  },
  {
    name: "Dropbox",
    image: "dropbox.png",
    summary: "Manage Dropbox files and folders with your agents",
    link: "/toolkits/productivity/dropbox",
    category: "productivity",
    type: "arcade",
  },
  {
    name: "Discord",
    image: "discord.png",
    summary: "Manage Discord servers, channels, and more with your agents",
    link: "/toolkits/social-communication/discord",
    category: "social",
    type: "auth",
  },
  {
    name: "Reddit",
    image: "reddit.png",
    summary: "Interact with Reddit with your agents",
    link: "/toolkits/social-communication/reddit",
    category: "social",
    type: "auth",
  },
  {
    name: "Twitch",
    image: "twitch.png",
    summary: "Create clips, get videos, and more from Twitch with your agents",
    link: "/toolkits/entertainment/twitch",
    category: "entertainment",
    type: "auth",
  },
];

// Coming soon tools
const comingSoonTools: Tool[] = [
  {
    name: "ADP Workforce Now",
    image: "adp.png",
    summary: "Manage payroll, HR, and workforce data with your agents.",
    link: "/toolkits/productivity/adp",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Aha",
    image: "aha.png",
    summary: "Manage product roadmaps and strategy with your agents.",
    link: "/toolkits/productivity/aha",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Airtable",
    image: "airtable.svg",
    summary: "Create, edit, and manage Airtable bases with your agents.",
    link: "/toolkits/productivity/airtable",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Amplitude",
    image: "amplitude.png",
    summary: "Analyze user behavior and product analytics with your agents.",
    link: "/toolkits/productivity/amplitude",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Asana",
    image: "asana.svg",
    summary: "Manage projects, tasks, and more in Asana with your agents.",
    link: "/toolkits/productivity/asana",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Ashby",
    image: "ashby.png",
    summary: "Manage recruiting and hiring processes with your agents.",
    link: "/toolkits/productivity/ashby",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Auth0",
    image: "auth0.svg",
    summary: "Manage authentication and authorization with your agents.",
    link: "/toolkits/development/auth0",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "BambooHR",
    image: "bamboohr.png",
    summary: "Manage employee data and HR processes with your agents.",
    link: "/toolkits/productivity/bamboohr",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Basecamp",
    image: "basecamp.png",
    summary: "Manage projects, tasks, and team communication with your agents.",
    link: "/toolkits/productivity/basecamp",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Bill.com",
    image: "bill.png",
    summary: "Manage invoices and payments with your agents.",
    link: "/toolkits/productivity/bill",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Bitbucket",
    image: "bitbucket.png",
    summary:
      "Manage repositories, pull requests, and pipelines with your agents.",
    link: "/toolkits/development/bitbucket",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Bluesky",
    image: "bluesky.svg",
    summary: "Interact with Bluesky with your agents.",
    link: "/toolkits/social-communication/bluesky",
    category: "social",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Box",
    image: "box.svg",
    summary: "Manage files and folders in Box with your agents.",
    link: "/toolkits/productivity/box",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Braze",
    image: "braze.png",
    summary: "Manage customer engagement campaigns with your agents.",
    link: "/toolkits/productivity/braze",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Brex",
    image: "brex.png",
    summary: "Manage business expenses and cards with your agents.",
    link: "/toolkits/productivity/brex",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Buffer",
    image: "buffer.png",
    summary: "Schedule and manage social media posts with your agents.",
    link: "/toolkits/social-communication/buffer",
    category: "social",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Calendly",
    image: "calendly.svg",
    summary: "Manage scheduling and appointments with your agents.",
    link: "/toolkits/productivity/calendly",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "ClickUp",
    image: "clickup.svg",
    summary: "Manage projects, tasks, and documents with your agents.",
    link: "/toolkits/productivity/clickup",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Coinbase",
    image: "coinbase.svg",
    summary: "Manage cryptocurrency transactions and wallets with your agents.",
    link: "/toolkits/productivity/coinbase",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Datadog",
    image: "datadog.svg",
    summary: "Monitor applications and infrastructure with your agents.",
    link: "/toolkits/development/datadog",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "DigitalOcean",
    image: "digitalocean.png",
    summary: "Manage cloud servers and infrastructure with your agents.",
    link: "/toolkits/development/digitalocean",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "eBay",
    image: "ebay.svg",
    summary: "Manage listings, orders, and inventory on eBay with your agents.",
    link: "/toolkits/productivity/ebay",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Evernote",
    image: "evernote.png",
    summary: "Create and manage notes with your agents.",
    link: "/toolkits/productivity/evernote",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Factorial",
    image: "factorial.png",
    summary: "Manage HR processes and employee data with your agents.",
    link: "/toolkits/productivity/factorial",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Figma",
    image: "figma.svg",
    summary: "Access design files and collaborate on designs with your agents.",
    link: "/toolkits/productivity/figma",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "GitLab",
    image: "gitlab.svg",
    summary:
      "Manage repositories, issues, and merge requests with your agents.",
    link: "/toolkits/development/gitlab",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Heroku",
    image: "heroku.svg",
    summary: "Deploy and manage applications on Heroku with your agents.",
    link: "/toolkits/development/heroku",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Hootsuite",
    image: "hootsuite.png",
    summary: "Manage and schedule social media content with your agents.",
    link: "/toolkits/social-communication/hootsuite",
    category: "social",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "HubSpot",
    image: "hubspot.png",
    summary:
      "Manage contacts, deals, and marketing campaigns in HubSpot with your agents.",
    link: "/toolkits/productivity/hubspot",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Intercom",
    image: "intercom.png",
    summary: "Manage customer communications and support with your agents.",
    link: "/toolkits/social-communication/intercom",
    category: "social",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Linear",
    image: "linear.svg",
    summary: "Manage issues and projects with your agents.",
    link: "/toolkits/productivity/linear",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Mailchimp",
    image: "mailchimp.png",
    summary: "Manage email campaigns and subscribers with your agents.",
    link: "/toolkits/productivity/mailchimp",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Microsoft Dynamics",
    image: "msft.png",
    summary: "Manage CRM and ERP processes with your agents.",
    link: "/toolkits/productivity/microsoft_dynamics",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Model Context Protocol (MCP)",
    image: "mcp.png",
    summary: "Manage context and improve AI interactions with your agents.",
    link: "/toolkits/development/mcp",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Miro",
    image: "miro",
    summary: "Create and collaborate on visual boards with your agents.",
    link: "/toolkits/productivity/miro",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Monday",
    image: "monday.png",
    summary: "Manage projects and workflows with your agents.",
    link: "/toolkits/productivity/monday",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Netsuite",
    image: "netsuite.svg",
    summary: "Manage financial and business operations with your agents.",
    link: "/toolkits/productivity/netsuite",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Okta",
    image: "okta.png",
    summary: "Manage identity and access with your agents.",
    link: "/toolkits/productivity/okta",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Pinecone",
    image: "pinecone.png",
    summary: "Manage vector databases and similarity search with your agents.",
    link: "/toolkits/development/pinecone",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Pinterest",
    image: "pinterest.svg",
    summary: "Create and manage pins and boards with your agents.",
    link: "/toolkits/social-communication/pinterest",
    category: "social",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Pipedrive",
    image: "pipedrive.png",
    summary: "Manage sales pipelines and leads with your agents.",
    link: "/toolkits/productivity/pipedrive",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Plaid",
    image: "plaid.png",
    summary:
      "Connect with financial accounts and manage financial data with your agents.",
    link: "/toolkits/productivity/plaid",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "QuickBooks",
    image: "quickbooks.png",
    summary: "Manage accounting and finances with your agents.",
    link: "/toolkits/productivity/quickbooks",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Salesforce",
    image: "salesforce.svg",
    summary: "Manage customer relationships and sales with your agents.",
    link: "/toolkits/productivity/salesforce",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Shopify",
    image: "shopify.svg",
    summary: "Manage e-commerce stores and products with your agents.",
    link: "/toolkits/productivity/shopify",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "SingleStore",
    image: "singlestore.png",
    summary: "Manage databases and data operations with your agents.",
    link: "/toolkits/development/singlestore",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Snowflake",
    image: "snowflake.png",
    summary: "Manage data warehouses and analytics with your agents.",
    link: "/toolkits/development/snowflake",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Splunk",
    image: "splunk.png",
    summary: "Monitor and analyze machine data with your agents.",
    link: "/toolkits/development/splunk",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Square",
    image: "square.png",
    summary:
      "Process payments and manage business operations with your agents.",
    link: "/toolkits/productivity/square",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Squarespace",
    image: "squarespace.png",
    summary: "Manage websites and online presence with your agents.",
    link: "/toolkits/productivity/squarespace",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Stripe",
    image: "stripe.svg",
    summary: "Process payments and manage subscriptions with your agents.",
    link: "/toolkits/productivity/stripe",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "TikTok",
    image: "tiktok.svg",
    summary: "Create and manage TikTok content with your agents.",
    link: "/toolkits/social-communication/tiktok",
    category: "social",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Trello",
    image: "trello.png",
    summary: "Manage boards, cards, and lists with your agents.",
    link: "/toolkits/productivity/trello",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Vercel",
    image: "vercel.svg",
    summary: "Deploy and manage web applications with your agents.",
    link: "/toolkits/development/vercel",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Weaviate",
    image: "weaviate.png",
    summary: "Manage vector databases and semantic search with your agents.",
    link: "/toolkits/development/weaviate",
    category: "development",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Workday",
    image: "workday.png",
    summary: "Manage HR, finance, and planning with your agents.",
    link: "/toolkits/productivity/workday",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Wrike",
    image: "wrike.png",
    summary: "Manage projects and collaborate with your agents.",
    link: "/toolkits/productivity/wrike",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Xero",
    image: "xero.svg",
    summary: "Manage accounting and finances with your agents.",
    link: "/toolkits/productivity/xero",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
  {
    name: "Zendesk",
    image: "zendesk.png",
    summary: "Manage customer support and service with your agents.",
    link: "/toolkits/productivity/zendesk",
    category: "productivity",
    type: "arcade",
    isComingSoon: true,
  },
];

// Merge and export all tools
export const tools: Tool[] = [...comingSoonTools, ...availableTools];
