auth:
  providers:
    - id: default-linkedin
      description: "The default LinkedIn provider"
      enabled: true
      type: oauth2
      provider_id: linkedin
      client_id: ${env:LINKEDIN_CLIENT_ID}
      client_secret: ${env:LINKEDIN_CLIENT_SECRET}
