auth:
  providers:
    - id: default-clickup
      description: "The default ClickUp provider"
      enabled: true
      type: oauth2
      provider_id: clickup
      client_id: ${env:CLICKUP_CLIENT_ID}
      client_secret: ${env:CLICKUP_CLIENT_SECRET}
