auth:
  providers:
    - id: arcade-calendly
      description: "Arcade's default Calendly provider"
      enabled: true
      type: oauth2
      provider_id: calendly
      client_id: ${env:CALENDLY_CLIENT_ID}
      client_secret: ${env:CALENDLY_CLIENT_SECRET}
