auth:
  providers:
    - id: hubspot
      description: "Custom Hubspot provider"
      enabled: true
      type: oauth2
      client_id: ${env:HUBSPOT_CLIENT_ID}
      client_secret: ${env:HUBSPOT_CLIENT_SECRET}
