# Telemetry
TELEMETRY_ENVIRONMENT=local
TELEMETRY_LOGGING_LEVEL=info
TELEMETRY_LOGGING_ENCODING=console

# API
API_DEVELOPMENT=true
ARCADE_API_HOST=localhost
ARCADE_API_PORT=9099
ANALYTICS_ENABLED=true

# Encryption keys (change this when deploying to production)
ROOT_KEY_1=default-key-value

# LLM
# OPENAI_API_KEY=
# ANTHROPIC_API_KEY=
# GROQ_API_KEY=

# Workers
ARCADE_WORKER_URI=http://localhost:8002
ARCADE_WORKER_SECRET=dev

# Redis
# REDIS_HOST=
# REDIS_PORT=

# OAuth Providers
ATLASSIAN_CLIENT_ID=""
ATLASSIAN_CLIENT_SECRET=

DISCORD_CLIENT_ID=""
DISCORD_CLIENT_SECRET=

DROPBOX_CLIENT_ID=""
DROPBOX_CLIENT_SECRET=

GITHUB_CLIENT_ID=""
GITHUB_CLIENT_SECRET=

GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=

LINKEDIN_CLIENT_ID=""
LINKEDIN_CLIENT_SECRET=

MICROSOFT_CLIENT_ID=""
MICROSOFT_CLIENT_SECRET=

SLACK_CLIENT_ID=""
SLACK_CLIENT_SECRET=

SPOTIFY_CLIENT_ID=""
SPOTIFY_CLIENT_SECRET=

X_CLIENT_ID=""
X_CLIENT_SECRET=

ZOOM_CLIENT_ID=""
ZOOM_CLIENT_SECRET=
