api:
  development: false
  host: localhost
  port: 9099

llm:
  models:
    - id: my-openai-model-provider
      openai:
        api_key: ${env:OPENAI_API_KEY}
        default_params:
          temperature: 0

tools:
  directors:
    - id: default
      enabled: true
      actors:
        - id: "localactor"
          enabled: true
          http:
            uri: "http://localhost:8002"
            timeout: 30
            retry: 3
            secret: ${env:ARCADE_ACTOR_SECRET}

auth:
  token_store:
    redis:
      addr: "redis:6379"
      password: ${env:REDIS_PASSWORD}

  providers:
    - id: github
      enabled: true
      client_id: ${env:GITHUB_CLIENT_ID}
      client_secret: ${env:GITHUB_CLIENT_SECRET}

    - id: hooli
      enabled: true
      type: oauth2
      client_id: ${env:HOOLI_CLIENT_ID}
      client_secret: ${env:HOOLI_CLIENT_SECRET}
      oauth2:
        # Connection details here...

telemetry:
  environment: local
  version: ${env:VERSION}
  logging:
    level: info
    encoding: console
