api:
  development: true

llm:
  models:
    - id: oai
      openai:
        api_key: ${env:OPENAI_API_KEY}

tools:
  directors:
    - id: default
      actors:
        - id: "localactor"
          enabled: true
          http:
            uri: "http://localhost:8002"
            timeout: 30
            retry: 3

auth:
  token_store:
    in_memory:
      max_size: 1000000

telemetry:
  environment: local
