auth:
  providers:
    - id: default-dropbox
      description: "The default Dropbox provider"
      enabled: true
      type: oauth2
      provider_id: dropbox
      client_id: ${env:DROPBOX_CLIENT_ID}
      client_secret: ${env:DROPBOX_CLIENT_SECRET}

