export default {
  dark: "Dark",
  light: "Light",
  system: "System",
  toc: {
    title: "On this page",
    backToTop: "Scroll to top",
  },
  lastUpdated: "Last updated on",
  notFound: "This page could not be found",
  poweredBy: "Powered by",
  editPage: "Edit this page on GitHub",
  by: "by",
  banner: {
    aiTranslation:
      "🤖 This translation is in progress and was generated by AI. If you find something incorrect or want to help improve it, please",
    contributeLink: "contribute on GitHub",
    thanks: "Thank you for your help!",
  },
  notFoundPage: {
    title: "Page not found",
    description: "This page doesn't exist or may have moved.",
    notAvailablePrefix: "Not available in",
    tryEnglish: "Try English version",
    translationHint: "This page may not be translated yet.",
    viewOriginalEnglish: "View the original in English",
    goHome: "Go to homepage",
    goBack: "Go back",
    needHelp: "Need help? Try these popular pages:",
    quickstart: "Quickstart",
    mcpServers: "MCP Servers",
    createMcpServer: "Create a MCP Server",
  },
};
