auth:
  providers:
    - id: default-notion
      description: "The default Notion provider"
      enabled: true
      type: oauth2
      provider_id: notion
      client_id: ${env:NOTION_CLIENT_ID}
      client_secret: ${env:NOTION_CLIENT_SECRET}
