auth:
  providers:
    - id: default-linear
      description: "The default Linear provider"
      enabled: true
      type: oauth2
      provider_id: linear
      client_id: ${env:LINEAR_CLIENT_ID}
      client_secret: ${env:LINEAR_CLIENT_SECRET}
