auth:
  providers:
    - id: arcade-pagerduty
      description: "Arcade's default PagerDuty provider"
      enabled: true
      type: oauth2
      provider_id: pagerduty
      client_id: ${env:PAGERDUTY_CLIENT_ID}
      client_secret: ${env:PAGERDUTY_CLIENT_SECRET}
