auth:
  providers:
    - id: default-reddit
      description: "The default Reddit provider"
      enabled: true
      type: oauth2
      provider_id: reddit
      client_id: ${env:REDDIT_CLIENT_ID}
      client_secret: ${env:REDDIT_CLIENT_SECRET}
