auth:
  providers:
    - id: arcade-airtable
      description: "Arcade's default Airtable provider"
      enabled: true
      type: oauth2
      provider_id: airtable
      client_id: ${env:AIRTABLE_CLIENT_ID}
      client_secret: ${env:AIRTABLE_CLIENT_SECRET}
