auth:
  providers:
    - id: hooli
      type: oauth2
      description: "Hooli OAuth 2.0 provider"
      enabled: true
      client_id: ${env:HOOLI_CLIENT_ID}
      client_secret: ${env:HOOLI_CLIENT_SECRET}
      oauth2:
        scope_delimiter: " "
        pkce: # Optional
          enabled: true
          code_challenge_method: "S256"
        authorization_request:
          endpoint: "https://example.com/oauth/authorize"
          params:
            response_type: "code"
            client_id: "{{client_id}}"
            redirect_uri: "{{redirect_uri}}"
            scope: "{{scopes}} {{existing_scopes}}"
        token_request:
          endpoint: "https://example.com/oauth/token"
          auth_method: "client_secret_basic" # Optional
          params:
            grant_type: "authorization_code"
            client_id: "{{client_id}}"
            client_secret: "{{client_secret}}"
            redirect_uri: "{{redirect_uri}}"
          response_content_type: "application/json" # Optional
          response_map: # Optional
            access_token: "$.access_token"
            refresh_token: "$.refresh_token"
            expires_in: "$.expires_in"
            scope: "$.scope"
        refresh_token_request: # Optional
          endpoint: "https://example.com/oauth/token"
          auth_method: "client_secret_basic" # Optional
          params:
            grant_type: "refresh_token"
            client_id: "{{client_id}}"
            client_secret: "{{client_secret}}"
            refresh_token: "{{refresh_token}}"
          response_content_type: "application/json" # Optional
          response_map: # Optional
            access_token: "$.access_token"
            refresh_token: "$.refresh_token"
            expires_in: "$.expires_in"
            scope: "$.scope"
        user_info_request: # Optional
          endpoint: "https://example.com/oauth/userinfo"
          auth_method: "bearer_access_token"
          response_content_type: "application/json"
          triggers:
            on_token_grant: true
            on_token_refresh: true
