auth:
  providers:
    - id: hooli
      type: oauth2
      description: "Hooli OAuth 2.0 provider"
      enabled: true
      client_id: "${env:HOOLI_CLIENT_ID}"
      client_secret: "${env:HOOLI_CLIENT_SECRET}"
      oauth2:
        # Server-specific configuration, see reference below
