auth:
  providers:
    - id: default-zoom
      description: "The default Zoom provider"
      enabled: true
      type: oauth2
      provider_id: zoom
      client_id: ${env:ZOOM_CLIENT_ID}
      client_secret: ${env:ZOOM_CLIENT_SECRET}
