export default {
  overview: "Overview",
  oauth2: "OAuth 2.0",
  airtable: "Airtable",
  asana: "Asana",
  atlassian: "Atlassian",
  calendly: "Calendly",
  clickup: "ClickUp",
  discord: "Discord",
  figma: "Figma",
  github: "GitHub",
  google: "Google",
  hubspot: "Hubspot",
  linear: "Linear",
  linkedin: "LinkedIn",
  mailchimp: "Mailchimp",
  microsoft: "Microsoft",
  miro: "Miro",
  notion: "Notion",
  pagerduty: "PagerDuty",
  reddit: "Reddit",
  salesforce: "Salesforce",
  slack: "Slack",
  spotify: "Spotify",
  square: "Square",
  ticktick: "TickTick",
  twitch: "Twitch",
  x: "X",
  zendesk: "Zendesk",
  zoho: "Zoho",
  zoom: "Zoom",
};
