auth:
  providers:
    - id: default-discord
      description: "The default Discord provider"
      enabled: true
      type: oauth2
      provider_id: discord
      client_id: ${env:DISCORD_CLIENT_ID}
      client_secret: ${env:DISCORD_CLIENT_SECRET}
