name: Changelog Agent

on:
  schedule:
    # Run every Saturday at 00:00 UTC
    - cron: '0 0 * * 6'
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch full history for git operations

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: agents/changelog
        run: bun install

      - name: Generate changelog
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd agents/changelog
          bun index.ts generate

      - name: Check for changes
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update changelog [skip ci]"
          title: "🤖 Automated changelog update"
          body: |
            This PR contains automated changelog updates generated by the changelog agent.

            **Generated on:** ${{ github.event_name == 'workflow_dispatch' && 'Manual trigger' || 'Scheduled run' }}
            **Triggered by:** ${{ github.actor }}

            The changelog agent has analyzed recent commits and pull requests to update the changelog with the latest changes.
          branch: chore/update-changelog-${{ github.run_id }}
          delete-branch: true
          labels: |
            automated
            changelog
          assignees: evantahler
