name: Generate LLMs.txt

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  llmstxt:
    name: Generate LLMSTXT
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.DOCS_PUBLISHABLE_GH_TOKEN }}

      - name: Install dependencies
        run: npm install -g pnpm

      - name: Install pnpm
        run: pnpm install

      - name: generate LLMs.txt
        run: pnpm llmstxt
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
